version: '3.8'

services:

  mongo:
    container_name: product-mongodb-poc
    image: mongo
    restart: always
    ports:
      - 7777:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: password1

  mongo-express:
    container_name: product-mongo-express-poc
    image: mongo-express
    restart: always
    ports:
      - 7799:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://user1:password1@mongo:27017/